### ISSUE TITLE
Need Tutorial for Admittance Control in Gazebo Simulation & Real Robot

### ISSUE THREAD

**Issue by YuHoChau** [wangarcher/ur5e_actual#1]
您好, 十分感谢您的分享。

请问能否方便提供一个导纳控制的基本教程呢。例如在[ur5e_simulation](https://github.com/wangarcher/ur5e_simulation)中如何对UR5进行导纳仿真。

此外，在`ur5e_actual`中的启动文件`admittance_controller.launch`中注意到`<arg name="F/T_sensor" default="false" />`，请问这个是怎么理解呢？UR5e是自带末端力传感器的，实际机器人受到的力是如何通过UR驱动获得的`/wrench`话题发送到`AdmittanceController`中行进行处理的么？所以本处`F/T_sensor`并没有作用？

最后请问以下实机上的导纳控制步骤是正确的吗：
`roslaunch ur_robot_driver ur5e_bringup_with_ip.launch`
`roslaunch ur5e_admittance_control admittance_controller.launch`

非常感谢，期待您的解答。

**Comment by wangarcher** [comment]
关于第一件事，如果急用推荐参考[epfl的工程](https://github.com/epfl-lasa/ridgeback_ur5_controller)，本工程的控制部分中的绝大多数代码均受该项目的启发。我后续会push一些导纳这方面的仿真工作上来，但不一定是什么时候了（笑）
关于第二件事，在实机操作中，机器人直接返回的六轴力传感器消息就是/wrench。建议先试试。
关于第三件事，如果导纳可以用的话，应该是正确的。
以上，祝好运。

**Comment by YuHoChau** [comment]
已解决。非常感谢您的回复。
